# base
seed: 0
deterministic: True

# environment config
device: cpu     # examples: [0], [0,1], [1,2,3], cpu... 

# project config
project: outputs/DCGAN
name: CelebA

# image setting config
img_size: 64
color_channel: 3
convert2grayscale: False

# data config
workers: 0               # Don't worry to set worker. The number of workers will be set automatically according to the batch size.
CelebA_train: True       # if True, CelebA will be loaded automatically.
CelebA:
    path: data/
CUSTOM:
    train_data_path: null
    validation_data_path: null
    test_data_path: null

# train config
batch_size: 128
epochs: 100
lr: 0.0002
beta1: 0.5
g_dim: 64
d_dim: 64
noise_init_size: 128

# logging config
common: ['train_loss_d', 'train_loss_g', 'validation_loss_d', 'validation_loss_g', 'd_x', 'd_g1', 'd_g2']